# Generated by Django 5.2.7 on 2025-12-14 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='positiveonlysocialuser',
            name='is_adult',
            field=models.BooleanField(default=False),
        ),
    ]
