# Generated by Django 5.2.5 on 2025-09-03 21:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('response_identifier', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('series_identifier', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('management_token', models.IntegerField(default=0)),
                ('post_identifier', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('image_url', models.TextField(null=True)),
                ('caption', models.TextField(null=True)),
                ('post_likes', models.IntegerField(default=0)),
                ('post_creation_time', models.DateTimeField(auto_now=True, null=True)),
                ('post_updated_time', models.DateTimeField(auto_now=True, null=True)),
                ('comment_thread_identifier', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('comment_thread_creation_time', models.DateTimeField(auto_now=True, null=True)),
                ('comment_thread_updated_time', models.DateTimeField(auto_now=True, null=True)),
                ('comment_identifier', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('author_username', models.TextField(null=True)),
                ('body', models.TextField(null=True)),
                ('comment_creation_time', models.DateTimeField(auto_now=True, null=True)),
                ('comment_updated_time', models.DateTimeField(auto_now=True, null=True)),
                ('comment_likes', models.IntegerField(default=0)),
            ],
        ),
    ]
