# Generated by Django 5.2.5 on 2025-09-11 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='reported',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='reported_by_username',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='reported_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='reported',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='reported_by_username',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='reported_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
