# Generated by Django 5.2.5 on 2025-09-21 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positiveonlysocialuser',
            name='reset_id',
            field=models.IntegerField(default=-1),
        ),
    ]
