# Generated by Django 5.2.7 on 2025-12-16 01:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_system', '0002_positiveonlysocialuser_is_adult'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user_blocked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by_set', to=settings.AUTH_USER_MODEL)),
                ('user_blocker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocking_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='positiveonlysocialuser',
            name='blocked',
            field=models.ManyToManyField(related_name='blocked_by', through='user_system.UserBlock', through_fields=('user_blocker', 'user_blocked'), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='userblock',
            constraint=models.UniqueConstraint(fields=('user_blocker', 'user_blocked'), name='unique_blocks'),
        ),
    ]
