# Generated by Django 5.2.5 on 2025-09-06 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_system', '0002_response'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='management_token',
        ),
        migrations.RemoveField(
            model_name='response',
            name='token',
        ),
        migrations.AddField(
            model_name='response',
            name='login_cookie_token',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='response',
            name='session_management_token',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='ip',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='management_token',
            field=models.TextField(null=True),
        ),
    ]
