# Generated by Django 6.0.6 on 2026-06-14 22:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_system', '0009_knowndevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='hidden_reason',
            field=models.TextField(blank=True, choices=[('', 'Not hidden'), ('reports', 'Reports'), ('classifier', 'Classifier')], default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='hidden_reason',
            field=models.TextField(blank=True, choices=[('', 'Not hidden'), ('reports', 'Reports'), ('classifier', 'Classifier')], default=''),
        ),
        migrations.CreateModel(
            name='Appeal',
            fields=[
                ('appeal_identifier', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('content_snapshot', models.TextField(blank=True, null=True)),
                ('status', models.TextField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied')], default='pending')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('resolved_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('resolution_note', models.TextField(blank=True, null=True)),
                ('appellant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appeals', to=settings.AUTH_USER_MODEL)),
                ('ban', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appeals', to='user_system.userban')),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appeals', to='user_system.comment')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appeals', to='user_system.post')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appeals_resolved', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('post__isnull', False), ('comment__isnull', False)), models.Q(('post__isnull', False), ('ban__isnull', False)), models.Q(('comment__isnull', False), ('ban__isnull', False)), _connector='OR', _negated=True), name='appeal_has_at_most_one_target')],
            },
        ),
    ]
