# Generated by Django 6.0.6 on 2026-06-15 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_system', '0010_comment_hidden_reason_post_hidden_reason_appeal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='hidden_reason',
            field=models.TextField(blank=True, choices=[('', 'Unspecified'), ('reports', 'Reports'), ('classifier', 'Classifier')], default=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='hidden_reason',
            field=models.TextField(blank=True, choices=[('', 'Unspecified'), ('reports', 'Reports'), ('classifier', 'Classifier')], default=''),
        ),
    ]
