# Generated by Django 6.0.6 on 2026-06-18 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_system', '0011_alter_comment_hidden_reason_alter_post_hidden_reason'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='appeal',
            constraint=models.UniqueConstraint(condition=models.Q(('post__isnull', False)), fields=('post',), name='unique_appeal_per_post'),
        ),
        migrations.AddConstraint(
            model_name='appeal',
            constraint=models.UniqueConstraint(condition=models.Q(('comment__isnull', False)), fields=('comment',), name='unique_appeal_per_comment'),
        ),
    ]
