# Generated by Django 5.2.15 on 2026-07-18 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_system', '0012_appeal_unique_appeal_per_post_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='knowndevice',
            name='unique_user_device_ip',
        ),
        migrations.AddField(
            model_name='knowndevice',
            name='user_agent',
            field=models.CharField(blank=True, default='',max_length=512),
        ),
        migrations.AddConstraint(
            model_name='knowndevice',
            constraint=models.UniqueConstraint(fields=('user', 'ip', 'user_agent'), name='unique_user_device_ip_user_agent'),
        ),
    ]
