# Generated by Django 5.2.7 on 2026-07-19 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_system', '0013_positiveonlysocialuser_email_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='classification_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='classification_reason_code',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='hidden_reason',
            field=models.TextField(blank=True, choices=[('', 'Unspecified'), ('reports', 'Reports'), ('classifier', 'Classifier'), ('pending_classification', 'Pending classification'), ('classifier_final', 'Classifier (final)')], default=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='hidden_reason',
            field=models.TextField(blank=True, choices=[('', 'Unspecified'), ('reports', 'Reports'), ('classifier', 'Classifier'), ('pending_classification', 'Pending classification'), ('classifier_final', 'Classifier (final)')], default=''),
        ),
    ]
