# Generated by Django 5.2.15 on 2026-07-18 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_system', '0013_positiveonlysocialuser_email_verification'),
        ('user_system', '0013_remove_knowndevice_unique_user_device_ip_and_more'),
    ]

    operations = [
    ]
