# Generated by Django 5.2.7 on 2026-07-20 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_system', '0014_post_classification_attempts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='classification_alerted',
            field=models.BooleanField(default=False),
        ),
    ]
