# Generated by Django 5.2.7 on 2026-07-21 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_system', '0014_merge_20260718_1549'),
        ('user_system', '0015_post_classification_alerted'),
    ]

    operations = [
    ]
