# Generated by Django 5.2.7 on 2026-07-20 00:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_system', '0015_post_classification_alerted'),
    ]

    operations = [
        migrations.AddField(
            model_name='positiveonlysocialuser',
            name='totp_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='positiveonlysocialuser',
            name='totp_last_used_step',
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='positiveonlysocialuser',
            name='totp_secret',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.CreateModel(
            name='RecoveryCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.TextField()),
                ('used_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_codes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TwoFactorChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.TextField()),
                ('expires', models.DateTimeField()),
                ('remember_me', models.BooleanField(default=False)),
                ('failed_attempts', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='two_factor_challenges', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
