# Generated by Django 5.2.7 on 2026-07-20 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_system', '0016_positiveonlysocialuser_totp_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twofactorchallenge',
            name='expires',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='twofactorchallenge',
            name='token_hash',
            field=models.TextField(db_index=True, unique=True),
        ),
    ]
