# Generated by Django 5.2.7 on 2026-07-23 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_system', '0018_alter_twofactorchallenge_expires_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='body_formatting',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='background_color',
            field=models.TextField(default='default'),
        ),
        migrations.AddField(
            model_name='post',
            name='caption_font',
            field=models.TextField(default='default'),
        ),
    ]
