# Generated by Django 5.2.7 on 2026-07-23 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_system', '0018_alter_twofactorchallenge_expires_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='positiveonlysocialuser',
            name='pending_profile_image_url',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='positiveonlysocialuser',
            name='profile_image_classification_alerted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='positiveonlysocialuser',
            name='profile_image_classification_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='positiveonlysocialuser',
            name='profile_image_classification_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='positiveonlysocialuser',
            name='profile_image_reason_code',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='positiveonlysocialuser',
            name='profile_image_status',
            field=models.TextField(default='none'),
        ),
        migrations.AddField(
            model_name='positiveonlysocialuser',
            name='profile_image_url',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
