# Generated by Django 5.2.7 on 2026-07-24 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_system', '0019_comment_body_formatting_post_background_color_and_more'),
        ('user_system', '0019_positiveonlysocialuser_pending_profile_image_url_and_more'),
    ]

    operations = [
    ]
