# Generated by Django 5.2.7 on 2026-07-24 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_system', '0020_merge_20260723_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='positiveonlysocialuser',
            name='membership_number',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, unique=True),
        ),
    ]
