# Generated by Django 5.2.7 on 2026-07-25 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_system', '0023_merge_saved_posts_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='positiveonlysocialuser',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
    ]
