# Generated by Django 5.2.7 on 2026-07-25 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_system', '0024_positiveonlysocialuser_bio'),
        ('user_system', '0024_tag_post_tags'),
    ]

    operations = [
    ]
