# Generated by Django 5.2.7 on 2026-07-27 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_system', '0026_userfollow_category_post_audience'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_blurhash',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
