# Generated by Django 5.2.7 on 2026-07-31 01:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_system', '0027_post_image_blurhash'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterestCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='positiveonlysocialuser',
            name='interest_categories',
            field=models.ManyToManyField(blank=True, related_name='interested_users', to='user_system.interestcategory'),
        ),
        migrations.AddField(
            model_name='post',
            name='interest_categories',
            field=models.ManyToManyField(blank=True, related_name='posts', to='user_system.interestcategory'),
        ),
        migrations.CreateModel(
            name='UserFreeformInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('creation_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_system.interestcategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freeform_interests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'text'), name='unique_user_freeform_interest')],
            },
        ),
    ]
