# Generated by Django 5.2.7 on 2026-07-31 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_system', '0029_notificationpreference'),
        ('user_system', '0029_seed_interest_categories'),
    ]

    operations = [
    ]
