# Generated by Django 5.2.7 on 2026-07-31 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_system', '0030_merge_20260730_2140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfreeforminterest',
            name='category',
        ),
        migrations.AddField(
            model_name='userfreeforminterest',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='+', to='user_system.interestcategory'),
        ),
    ]
