# Generated by Django 5.2.7 on 2026-07-31 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_system', '0030_comment_audience'),
        ('user_system', '0031_freeform_interest_categories'),
    ]

    operations = [
    ]
