# Generated by Django 5.2.7 on 2026-08-06 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_system', '0032_merge_20260731_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='positiveonlysocialuser',
            name='google_sub',
            field=models.TextField(blank=True, default=None, null=True, unique=True),
        ),
    ]
