# Generated by Django 5.2.7 on 2026-08-06 17:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_system', '0032_merge_20260731_1310'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModerationReview',
            fields=[
                ('review_identifier', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('status', models.TextField(choices=[('pending', 'Pending automated review'), ('cleared', 'Cleared by automated review'), ('escalated', 'Escalated to a moderator'), ('hidden', 'Content hidden'), ('dismissed', 'Reports dismissed')], default='pending')),
                ('reports_at_last_review', models.IntegerField(default=0)),
                ('review_attempts', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('reviewed_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('resolved_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('resolution_note', models.TextField(blank=True, null=True)),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='user_system.comment')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='user_system.post')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_reviews_resolved', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('post__isnull', False), ('comment__isnull', True)), models.Q(('post__isnull', True), ('comment__isnull', False)), _connector='OR'), name='moderation_review_has_exactly_one_target'), models.UniqueConstraint(condition=models.Q(('post__isnull', False)), fields=('post',), name='unique_review_per_post'), models.UniqueConstraint(condition=models.Q(('comment__isnull', False)), fields=('comment',), name='unique_review_per_comment')],
            },
        ),
    ]
