# Generated by Django 5.2.7 on 2026-08-06 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_system', '0033_moderationreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentreport',
            name='retracted_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='postreport',
            name='retracted_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
