# Generated by Django 5.2.7 on 2026-08-08 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_system', '0033_positiveonlysocialuser_google_sub'),
        ('user_system', '0034_commentreport_retracted_time_and_more'),
    ]

    operations = [
    ]
