# Generated by Django 5.2.7 on 2026-08-08 03:17
#
# Rejoins the two independent branches off 0032: the Google sign-in field
# (0033_positiveonlysocialuser_google_sub) and the moderation-review /
# report-retraction chain that the profile-photo BlurHash field now extends
# (0035). No operations — it exists only to give the graph a single leaf.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_system', '0033_positiveonlysocialuser_google_sub'),
        ('user_system', '0035_positiveonlysocialuser_profile_image_blurhash'),
    ]

    operations = [
    ]
