# Generated by Django 5.2.7 on 2026-09-21 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_system', '0036_merge_20260807_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='classification_model_chain',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='comment',
            name='classification_models_tried',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='post',
            name='classification_model_chain',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='post',
            name='classification_models_tried',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
