# Generated by Django 5.2.7 on 2026-09-23 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_system', '0037_post_comment_classification_model_chain'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comments_disabled',
            field=models.BooleanField(default=False),
        ),
    ]
