POSITIVE_IMAGE_URL = 'https://test-bucket.s3.amazonaws.com/positive_image_url.png'
NEGATIVE_IMAGE_URL = 'https://test-bucket.s3.amazonaws.com/negative_image_url.png'
POSITIVE_TEXT = 'positive'
NEGATIVE_TEXT = 'negative'
GEMINI_MODEL = 'gemini-2.5-flash'