//
//  GoogleSignIn.swift
//  Positive Only Social
//
//  Google sign-in (issue #10).
//
//  Deliberately no GoogleSignIn-iOS SDK. The whole native flow is an OAuth 2.0
//  authorization-code exchange with PKCE, which ASWebAuthenticationSession and
//  URLSession already do — and adding an SDK would pull AppAuth,
//  GTMAppAuth and GTMSessionFetcher into a project that currently resolves one
//  Swift package, plus their target-membership fallout in the test targets.
//
//  ASWebAuthenticationSession also means the custom redirect scheme needs no
//  CFBundleURLTypes entry: it intercepts the callback itself. The app's
//  Info.plist is generated by Xcode (GENERATE_INFOPLIST_FILE), so that matters.
//
//  Nothing here decides who anyone is. The ID token this produces is posted to
//  login/google/, and the backend verifies it against Google's public keys.
//

import AuthenticationServices
import CryptoKit
import Foundation
import UIKit

// MARK: - Configuration

/// The iOS OAuth client ID from the Google Cloud console.
///
/// Public by design (it ships inside every copy of the app; PKCE, not a secret,
/// is what protects the exchange), but empty here so the repository carries no
/// project-specific identifier. Fill it in — or leave it blank and Google
/// sign-in is simply not offered, the same "unset means the feature is off"
/// rule the backend and the website follow.
///
/// Whatever is set here must also appear in the backend's
/// GOOGLE_OAUTH_CLIENT_IDS, or every token this produces is rejected.
enum GoogleSignInConfig {
    static let clientID = ""
}

// MARK: - Errors

enum GoogleSignInError: Error, LocalizedError, Equatable {
    /// No client ID is configured, so the flow could never complete.
    case notConfigured
    /// The user dismissed Google's sheet. Not an error to show them.
    case cancelled
    case invalidConfiguration
    case invalidCallback
    case tokenExchangeFailed(String)

    var errorDescription: String? {
        switch self {
        case .notConfigured:
            return "Google sign-in is not set up in this build."
        case .cancelled:
            return "Google sign-in was cancelled."
        case .invalidConfiguration:
            return "Google sign-in is misconfigured in this build."
        case .invalidCallback:
            return "Google returned an unexpected response. Please try again."
        case .tokenExchangeFailed(let message):
            return "Google sign-in failed: \(message)"
        }
    }
}

// MARK: - Pure OAuth pieces

/// Everything one authorization attempt needs to carry through to the exchange.
struct GoogleAuthorizationRequest: Equatable {
    let url: URL
    let codeVerifier: String
    let state: String
    let redirectURI: String
    let callbackScheme: String
}

/// The stateless parts of the flow, kept free of UIKit and URLSession so each
/// one can be unit-tested on its own.
enum GoogleOAuth {
    static let authorizationEndpoint = "https://accounts.google.com/o/oauth2/v2/auth"
    static let tokenEndpoint = "https://oauth2.googleapis.com/token"

    /// Google's redirect scheme for an iOS client is the client ID's segments
    /// reversed: `123-abc.apps.googleusercontent.com` becomes
    /// `com.googleusercontent.apps.123-abc`.
    static func reversedClientID(for clientID: String) -> String? {
        let suffix = ".apps.googleusercontent.com"
        guard clientID.hasSuffix(suffix) else { return nil }
        let identifier = String(clientID.dropLast(suffix.count))
        guard !identifier.isEmpty else { return nil }
        return "com.googleusercontent.apps." + identifier
    }

    /// A high-entropy PKCE code verifier: 32 random bytes, base64url-encoded,
    /// which lands in RFC 7636's required 43-128 character range.
    static func makeCodeVerifier() -> String {
        // SystemRandomNumberGenerator is the platform CSPRNG on Apple systems.
        let bytes = (0..<32).map { _ in UInt8.random(in: UInt8.min...UInt8.max) }
        return base64URLEncode(Data(bytes))
    }

    /// The S256 challenge Google will check the verifier against.
    static func codeChallenge(for verifier: String) -> String {
        let digest = SHA256.hash(data: Data(verifier.utf8))
        return base64URLEncode(Data(digest))
    }

    static func base64URLEncode(_ data: Data) -> String {
        data.base64EncodedString()
            .replacingOccurrences(of: "+", with: "-")
            .replacingOccurrences(of: "/", with: "_")
            .replacingOccurrences(of: "=", with: "")
    }

    /// Build the authorization URL and the secrets that must survive until the
    /// exchange. `nonce` is included because Google binds it into the ID token.
    static func authorizationRequest(clientID: String) -> GoogleAuthorizationRequest? {
        guard let reversed = reversedClientID(for: clientID) else { return nil }
        let redirectURI = reversed + ":/oauth2redirect"
        let verifier = makeCodeVerifier()
        let state = makeCodeVerifier()

        guard var components = URLComponents(string: authorizationEndpoint) else { return nil }
        components.queryItems = [
            URLQueryItem(name: "client_id", value: clientID),
            URLQueryItem(name: "redirect_uri", value: redirectURI),
            URLQueryItem(name: "response_type", value: "code"),
            // openid+email is what the backend needs; profile is not requested
            // because nothing here uses a display name or a photo.
            URLQueryItem(name: "scope", value: "openid email"),
            URLQueryItem(name: "code_challenge", value: codeChallenge(for: verifier)),
            URLQueryItem(name: "code_challenge_method", value: "S256"),
            URLQueryItem(name: "state", value: state),
            URLQueryItem(name: "nonce", value: makeCodeVerifier()),
        ]
        guard let url = components.url else { return nil }

        return GoogleAuthorizationRequest(
            url: url,
            codeVerifier: verifier,
            state: state,
            redirectURI: redirectURI,
            callbackScheme: reversed
        )
    }

    /// Pull the authorization code out of Google's redirect.
    ///
    /// The `state` check is the CSRF defence: a callback that did not come from
    /// the request we just made is discarded rather than exchanged.
    static func authorizationCode(from callbackURL: URL, expectedState: String) throws -> String {
        guard let components = URLComponents(url: callbackURL, resolvingAgainstBaseURL: false),
              let items = components.queryItems else {
            throw GoogleSignInError.invalidCallback
        }
        func value(_ name: String) -> String? {
            items.first { $0.name == name }?.value
        }
        // Google reports a refusal as ?error=access_denied rather than a failure.
        if let error = value("error") {
            throw error == "access_denied"
                ? GoogleSignInError.cancelled
                : GoogleSignInError.tokenExchangeFailed(error)
        }
        guard value("state") == expectedState else { throw GoogleSignInError.invalidCallback }
        guard let code = value("code"), !code.isEmpty else { throw GoogleSignInError.invalidCallback }
        return code
    }

    /// The form-encoded POST that trades the code for an ID token. No client
    /// secret: an installed app is a public OAuth client, and the code verifier
    /// is what proves this is the same app that started the flow.
    static func tokenRequest(clientID: String, code: String, codeVerifier: String, redirectURI: String) -> URLRequest? {
        guard let url = URL(string: tokenEndpoint) else { return nil }
        var request = URLRequest(url: url)
        request.httpMethod = GVOAppConstants.post
        request.setValue("application/x-www-form-urlencoded", forHTTPHeaderField: GVOAppConstants.httpHeaderField)

        var components = URLComponents()
        components.queryItems = [
            URLQueryItem(name: "client_id", value: clientID),
            URLQueryItem(name: "code", value: code),
            URLQueryItem(name: "code_verifier", value: codeVerifier),
            URLQueryItem(name: "grant_type", value: "authorization_code"),
            URLQueryItem(name: "redirect_uri", value: redirectURI),
        ]
        request.httpBody = components.percentEncodedQuery?.data(using: .utf8)
        return request
    }

    private struct TokenResponse: Decodable {
        let id_token: String?
        let error: String?
        let error_description: String?
    }

    /// The ID token from a token-endpoint response, or a described failure.
    static func idToken(fromTokenResponse data: Data) throws -> String {
        guard let response = try? JSONDecoder().decode(TokenResponse.self, from: data) else {
            throw GoogleSignInError.invalidCallback
        }
        if let idToken = response.id_token, !idToken.isEmpty {
            return idToken
        }
        throw GoogleSignInError.tokenExchangeFailed(
            response.error_description ?? response.error ?? "no ID token was returned"
        )
    }
}

// MARK: - Provider

/// Injectable so views (and tests) never reach for ASWebAuthenticationSession.
protocol GoogleSignInProviding {
    /// False when no client ID is configured, in which case the button is hidden.
    var isConfigured: Bool { get }
    /// Run the flow and return a Google ID token to post to the backend.
    func signIn() async throws -> String
}

/// The real flow: Google's consent screen in an ASWebAuthenticationSession,
/// then a PKCE code exchange.
final class GoogleSignInProvider: NSObject, GoogleSignInProviding, ASWebAuthenticationPresentationContextProviding {
    private let clientID: String
    private let urlSession: URLSession

    init(clientID: String = GoogleSignInConfig.clientID, urlSession: URLSession = .shared) {
        self.clientID = clientID
        self.urlSession = urlSession
    }

    var isConfigured: Bool {
        GoogleOAuth.reversedClientID(for: clientID.trimmingCharacters(in: .whitespaces)) != nil
    }

    func signIn() async throws -> String {
        guard isConfigured else { throw GoogleSignInError.notConfigured }
        guard let request = GoogleOAuth.authorizationRequest(clientID: clientID) else {
            throw GoogleSignInError.invalidConfiguration
        }

        let callbackURL = try await presentAuthorization(request)
        let code = try GoogleOAuth.authorizationCode(from: callbackURL, expectedState: request.state)

        guard let tokenRequest = GoogleOAuth.tokenRequest(
            clientID: clientID,
            code: code,
            codeVerifier: request.codeVerifier,
            redirectURI: request.redirectURI
        ) else {
            throw GoogleSignInError.invalidConfiguration
        }

        // The status code is not consulted: Google explains itself in the body
        // on success and failure alike, and idToken(fromTokenResponse:) turns
        // an error body into a message worth showing instead of a bare 400.
        let (data, _) = try await urlSession.data(for: tokenRequest)
        return try GoogleOAuth.idToken(fromTokenResponse: data)
    }

    @MainActor
    private func presentAuthorization(_ request: GoogleAuthorizationRequest) async throws -> URL {
        try await withCheckedThrowingContinuation { continuation in
            let session = ASWebAuthenticationSession(
                url: request.url,
                callbackURLScheme: request.callbackScheme
            ) { callbackURL, error in
                if let callbackURL {
                    continuation.resume(returning: callbackURL)
                    return
                }
                let cancelled = (error as? ASWebAuthenticationSessionError)?.code == .canceledLogin
                continuation.resume(throwing: cancelled ? GoogleSignInError.cancelled : GoogleSignInError.invalidCallback)
            }
            session.presentationContextProvider = self
            // Do not reuse a Safari session: a shared cookie jar would sign the
            // user straight back into the Google account they just switched away
            // from, with no chance to pick another.
            session.prefersEphemeralWebBrowserSession = true
            session.start()
        }
    }

    func presentationAnchor(for session: ASWebAuthenticationSession) -> ASPresentationAnchor {
        let scene = UIApplication.shared.connectedScenes
            .compactMap { $0 as? UIWindowScene }
            .first { $0.activationState == .foregroundActive }
        return scene?.keyWindow ?? ASPresentationAnchor()
    }
}

/// Stands in for Google under UI tests, where no real consent screen can be
/// driven. Mirrors StatefulStubbedAPI: it returns an unsigned token carrying
/// exactly the claims the stubbed backend reads back out.
final class StubbedGoogleSignIn: GoogleSignInProviding {
    private let email: String

    init(email: String = "stubgoogleuser@example.com") {
        self.email = email
    }

    var isConfigured: Bool { true }

    func signIn() async throws -> String {
        let header = GoogleOAuth.base64URLEncode(Data(#"{"alg":"none"}"#.utf8))
        let claims = #"{"sub":"stub-google-sub","email":"\#(email)","email_verified":true}"#
        let payload = GoogleOAuth.base64URLEncode(Data(claims.utf8))
        return "\(header).\(payload).stubsignature"
    }
}
